sudo: false
language: node_js
node_js:
  - "6"

cache:
  yarn: true
  directories:
    - node_modules
before_install:
  # CI server install taobao npm packages too slow.
  - rm -rf ./yarn.lock

script:
  - yarn lint
  - yarn build
